### ISSUE TITLE
Final code update and blocks for code freeze

### ISSUE THREAD

**Issue by roglos** [roglos/uogmoodle#19]
All code updates and new blocks to be added pre-code freeze on Fri 2nd Sept

**Comment by roglos** [comment]
Updates available:
Core code - not being updated, unless bugs, going with current Moodle 3.1.1+ (Build: 20160721) as tested
Completion Progress
Configurable reports
Progress Bar - to be removed MdR is no longer going to be supporting this and will be migrating to Completion Progress plugin
Generico filter
Ad-Hoc database queries

**Comment by roelmann** [comment]
Also UserTours plugin to be added

Other potential additions:
H5P
BigBlueButton (maybe on test as this will link to a test server for now)

**Comment by roglos** [comment]
Transferred to LIVE and TEST
